### ISSUE TITLE
Fix json-server path location.

### ISSUE THREAD

**Issue by JoeDravarol** [Caleb-Cohen/Together#103]
# Summary
Currently the `dev` script in the client folder is pointing to the incorrect json file. We need to fix that by pointing back to the correct test json-server file and remove the z-code tutorial json file.

# Tasks
## Step 1
* Delete `client/src/services/events.json`.
* Update the client package.json file `dev` script path pointing to `src/test/events.json`.
* Test that the script work as expected.

## Step 2
* Add new scripts to the root package.json file.
Note: You want to add it under `start-client` script.
```json
"start-mockServer": "npm --prefix client run dev",
"dev-concurrent-mockServer": "concurrently \"npm:start-client\" \"npm:start-mockServer\"",
```
* Test that the script work as expected.

**Comment by code2244** [comment]
I will like to work on this issue.

**Comment by Caleb-Cohen** [comment]
Fixed by @code2244
