### ISSUE TITLE
Use login auth to prevent users from completing the add-event-form

### ISSUE THREAD

**Issue by Caleb-Cohen** [Caleb-Cohen/Together#109]
**Please provide a summary of the feature**
Only logged-in users should be able to complete the add-event form. The form can be hidden or just locked from submission. The choice is yours.

**Are there any potential issues you foresee with this feature**
I could foresee some issues with how the backend interacts with the frontend. 

**Is this feature related to any current or past issues? Please provide the #**
Related to discord Auth: #21 
Add-event form: #82 

@WinstonHall - can you comment so I can assign you?

**Comment by WinstonHall** [comment]
beep

**Comment by Caleb-Cohen** [comment]
@MatthewBozin, can you comment?

**Comment by luciousmc** [comment]
I am interested in taking part in this issue as well!

**Comment by MatthewBozin** [comment]
Happy to take this issue on

**Comment by Caleb-Cohen** [comment]
> Happy to take this issue on

Assigned. Can you coordinate with @luciousmc on some time you're working on this for some potential peer programming?

**Comment by Caleb-Cohen** [comment]
@MatthewBozin pr to branch feature/formSecurity

**Comment by luciousmc** [comment]
i'm usually on Discord under brotahman. Was this issue already completed?

**Comment by Caleb-Cohen** [comment]
> i'm usually on Discord under brotahman. Was this issue already completed?

It was PR'd today, yes.
