### ISSUE TITLE
Create Modal/Popout for events so users can view more information.

### ISSUE THREAD

**Issue by Caleb-Cohen** [Caleb-Cohen/Together#112]
**Please provide a summary of the feature**
Currently, the calendar only shows the time and event title. Users need to be able to see more event information like description, who's coordinating the event, and where the event will be. We will call this the event-details views

**Additional context**
Natalie provided a really good design here that can be used later, the only thing missing is the user that created the event is included. 

**Design does a great job, but we do not need editing for the MVP,** focus on core-functionality. We will make it look nice and add complexity later. 

<img width="653" alt="Screen Shot 2022-11-26 at 1 50 56 PM" src="https://user-images.githubusercontent.com/75268174/204106673-b9465acb-e6b2-4e44-8fd5-eb6aeb6fb4af.png">

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by InstincDev** [comment]
I would like to take on this issue.

**Comment by Caleb-Cohen** [comment]
All yours!
