### ISSUE TITLE
Landing Page Front End

### ISSUE THREAD

**Issue by Caleb-Cohen** [Caleb-Cohen/Together#121]
**Please provide a summary of the feature**
This task is to develop and implement a landing page using @Natashka333 design located [Here.](https://github.com/Caleb-Cohen/Together/discussions/17) Please use React for the landing page. 

This issue is for the front end only. While we'll need a button, it doesn't need to work.

**Are there any potential issues you foresee with this feature**

**Is this feature related to any current or past issues? Please provide the #**
Not related to any past issue directly.

**Additional context**
Natalie's designs were done in Figma. While I've never tried it there seem to be some [resources](https://www.figma.com/community/plugin/949398715671878472) on automating the design directly into React.

I've attached the design below, but please work with Natalie on the design.

*If you're interested in working on this feature, please comment so you can be assigned*

<img width="378" alt="Screen Shot 2022-11-30 at 9 35 52 AM" src="https://user-images.githubusercontent.com/75268174/204841007-5b949b5f-8588-429b-acd3-5db825744381.png">

**Comment by HondaChan14** [comment]
Hello could I help contribute to this? :o

**Comment by Caleb-Cohen** [comment]
> Hello could I help contribute to this? :o

Yes! Please PR into [feature/landingPage](https://github.com/Caleb-Cohen/Together/tree/feature/landingPage)

**Comment by HondaChan14** [comment]
> 
Awesome! tysm! I will each out to @Natashka333 :)

**Comment by TreLynnnn** [comment]
Hey, jumping in on this with @HondaChan14 !

**Comment by Nim-droid-droid** [comment]
Hey i would like to contribute to this.

**Comment by Caleb-Cohen** [comment]
@HondaChan14 You are the team lead on this. Please let @Nim-droid-droid know how y'all are getting together to work on this. If there's no compatible time, we can reassign @Nim-droid-droid to another task.

**Comment by HondaChan14** [comment]
> Hey i would like to contribute to this.

Hello @Nim-droid-droid  yes you can with me and @TreLynnnn . My discord name is Honda Civic Chan#4938. We plan on working on it today. Pls add me and dm for info. Thanks :)

**Comment by khanhtranngoccva** [comment]
I'd like to aid in creating the frontend landing page. 😄

**Comment by Caleb-Cohen** [comment]
> I'd like to aid in creating the frontend landing page. 😄

Hey there Khanh! This team may be full, but @HondaChan14 can speak to that. We will have other front-end-related development tasks opening up shortly. What is your React experience so I can tag you accordingly?

**Comment by khanhtranngoccva** [comment]
I'm familiar with most of React base concepts, including effects, state and contexts! I can also work with Tailwind as well. 😄

**Comment by Caleb-Cohen** [comment]
> I'm familiar with most of React base concepts, including effects, state and contexts! I can also work with Tailwind as well. 😄

Awesome! Give me until Monday, and I will have an issue for you to work on. Does that work?

**Comment by Caleb-Cohen** [comment]
> I'm familiar with most of React base concepts, including effects, state and contexts! I can also work with Tailwind as well. 😄

Apologies for the delay, but I have opened up #176 #175 #173
