### ISSUE TITLE
Have Together Not Require a Build Folder in Development

### ISSUE THREAD

**Issue by Caleb-Cohen** [Caleb-Cohen/Together#122]
**Please provide a summary of the feature**
We want to cease using the build folder for development, but to do that. 

1. The `Login with discord` needs to work from localhost:3000 (Frontend). Currently, the button only works out of `localhost:2121`.
2. The `Login with discord` button needs to redirect back to `localhost:3000`
3. These changes need to catch if we're running in development or production so it redirects properly. Rascal_Two provided insight on how that is accomplished [here.](https://discord.com/channels/735923219315425401/1038482732633825442/1047323290907201636)

<img width="779" alt="Screen Shot 2022-11-30 at 4 20 38 PM" src="https://user-images.githubusercontent.com/75268174/204920681-3df58f79-8c16-40f2-a3b8-724d4004770b.png">

**Are there any potential issues you foresee with this feature**
Production can break if this is not implemented correctly, @Caleb-Cohen should switch cyclic to this branch to test prior to merging into Development. 

**Is this feature related to any current or past issues? Please provide the #**
#116 and #117

**Additional context**
PR to branch `feature/noDevBuild` 

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by JoeSangine** [comment]
I shall try

**Comment by Caleb-Cohen** [comment]
@JoeSangine Great work!
