### ISSUE TITLE
Revise event schema and add an array of objects for recurring events

### ISSUE THREAD

**Issue by intelagense** [Caleb-Cohen/Together#126]
# Intro
This issue has been opened specifically to give 100Devs members a chance to get involved. The issues presented will have more instruction and be easier to solve. (If you are already contributing to this project or your skills are well ahead of this issue, consider letting someone else take this on!)

## Summary
Together needs a way to store the recurring events in the database after they are generated. 

You will need to make some changes to the existing model schema to accommodate implementing recurring dates.

This will involve using an array in the MongoDB document to embed objects for each event as well as combining the existing start/end dates and times into two distinct Date objects. 

## Tasks
You will only need to edit `/server/models/Event.js` 
* `startDate` and `startTime` will be combined into a single Date type 
* `endDate` and `endTime` will be combined into a single Date type
* `recurringRate` will be renamed to `recurring` and be a required boolean type 
* `recurringDates` array will be used to embed recurring events
    * each object in the array represents a unique editable event and will be used to contain its own copy of the event's title, description, start date/time, end date/time, location, and ~~Discord username~~.
    * `recurringDates` will be `require: false`

### Steps 

A feature branch named `feature/modify-event-schema` has been created for this specific issue. The [contributing guidelines](https://github.com/Caleb-Cohen/Together/blob/development/.github/CONTRIBUTING.md) contain the detailed walkthrough of the steps listed below.

1. Fork the development branch, clone it to your device, and check out the `feature/modify-event-schema` branch.
1. Create and check out an additional branch with a descriptive name on your device.
1. Edit the `/server/models/Event.js` file with the appropriate changes
1. Commit your work. 
1. Push your changes to GitHub.
1. Submit a pull request from GitHub.

## Potential Issues
Some minor alterations or additional changes may be requested during testing.

## Additional Notes and reference links
🚨 [6 Rules of thumb for MongoDB schema design.](https://www.mongodb.com/blog/post/6-rules-of-thumb-for-mongodb-schema-design)
🚨 [MongoDB schema design best practices.](https://www.mongodb.com/developer/products/mongodb/mongodb-schema-design-best-practices/)

---
**When completed please ensure you are creating a pull request into the development branch, instead of main.**

**Please comment below if you'd like to take this issue on.**  👇

**Comment by Caleb-Cohen** [comment]
Would Date FNS be used for part of this? Should that be included in the steps?

**Comment by intelagense** [comment]
I have edited the issue to add a couple of links to articles that I think will be helpful.

**Comment by JoeSangine** [comment]
hello

**Comment by intelagense** [comment]
Edited the issue. We do not need to include the Discord username in the array because the events are non-transferable.

**Comment by Caleb-Cohen** [comment]
Completed with #143. Will open a new issue to get this feature fully functional.
