### ISSUE TITLE
Create SPA routing for rendering landing page or calendar page

### ISSUE THREAD

**Issue by JoeDravarol** [Caleb-Cohen/Together#132]
### Intro
This issue has been opened specifically to give 100Devs members a chance to get involved. The issues presented will have more instruction and be easier to solve. If you are already contributing to this project or your skills are well-ahead of this issue, consider letting someone else take this on!

## Summary

Together needs a way to navigate between the landing page and the calendar page.

## Helpful resources

**React State**
* [State: A Component's Memory](https://beta.reactjs.org/learn/state-a-components-memory)

* Read from **Stateful component** to **Event handler is a function**.
[Stateful component](https://fullstackopen.com/en/part1/component_state_event_handlers#stateful-component)

* If you prefer video format watch this: [Using useState hook](https://www.youtube.com/watch?v=4pO-HcG2igk)

**Conditional Rendering**
* [Conditional Rendering](https://beta.reactjs.org/learn/conditional-rendering)

* if you prefer video format watch this: [Conditional Rendering](https://www.youtube.com/watch?v=4oCVDkb_EIs)

## Tasks
You will only need to edit `client/src/App.js`.

You want to create a state to keep track of which component/page `App.js` should display on the screen.

1. Create a state with useState hook (The state should have a clear and understandable name)

2. Conditional render a component based on the previous created state. You want to render either the landing page/component or the calendar page/component.

### Getting Started
A feature branch named `feature/SPA-routing` has been created for this specific issue. The [contributing guidelines]((https://github.com/Caleb-Cohen/Together/blob/development/.github/CONTRIBUTING.md) contain the detgailed walkthrough of the steps listed below:

1. Fork the development branch, clone it to your local machine, and check out the `feature/SPA-routing` branch.
3. Create and checkout an additional branch with a descriptive name on your local machine.
4. Edit the `client/src/App.js` file with the approriate changes.
5. Commit your work.
6. Push the changes to Github.
7. Submit a pull request from Github.

## Potential Issues

There will be a minor merge conflicts with `feature/landingPage` branch that needs to be resolved.

<hr>

**When completed please ensure you are creating a pull request into the development branch, instead of main.**

**Please comment on this issue if you'd like to take it on.**

**Comment by JoeDravarol** [comment]
@code2244 will be assigned to this issue.

**Comment by code2244** [comment]
hi, I will like to work on this issue.

**Comment by Caleb-Cohen** [comment]
Done!
