### ISSUE TITLE
Readme Improvements

### ISSUE THREAD

**Issue by Caleb-Cohen** [Caleb-Cohen/Together#136]
**Please provide a summary of the feature**
Readme has been one of the more antiquated development portions and could use some improvements. I'd like the enhancements to reinvent readme into a more approachable, minimal, and visually appealing one.

Some features that I would like to see, but are not limited to just the list below.
- Removal of setup instructions from Readme and direct users to the contributing.md and wiki
- Add some beautification to it! Buttons, photos, hopefully matching Natalie's design color.
- Add [deploy to cyclic button](https://docs.cyclic.sh/how-to/create-deploy-to-cyclic-button)
- Remove tasks 

PR directly into the development branch

This has been assigned to @praxeds - Please coordinate with her if you're interested in helping her out.

**Comment by praxeds** [comment]
In the works already 💪🏼

**Comment by Caleb-Cohen** [comment]
Completed!
