### ISSUE TITLE
Fix 👻 minutes bug

### ISSUE THREAD

**Issue by Caleb-Cohen** [Caleb-Cohen/Together#146]
**Please provide a summary of the feature**
<img width="386" alt="Screen Shot 2022-12-08 at 2 16 43 PM" src="https://user-images.githubusercontent.com/75268174/206558837-098a077a-d919-4d20-8960-948b691778ba.png">

will provide a better summary later

**Are there any potential issues you foresee with this feature**

**Is this feature related to any current or past issues? Please provide the #**

**Additional context**

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by WonjaeSung** [comment]
May I try to fix this bug?

**Comment by Caleb-Cohen** [comment]
> May I try to fix this bug?

Yes. Do you need any further explanation on the issue? I can type it up if you're having trouble.

**Comment by WonjaeSung** [comment]
That would be helpful. At the moment, I am connected to a dummy server and that's not giving me the error that Eric described you guys were experiencing.

**Comment by Caleb-Cohen** [comment]
> That would be helpful. At the moment, I am connected to a dummy server and that's not giving me the error that Eric described you guys were experiencing.

Rascal believes this issue appears with how we're parsing the event object. Currently we are using parseISO for the dates, when we should be using parseJSON. Tagging @rascalTwo for visibility.

**Comment by Caleb-Cohen** [comment]
> > > That would be helpful. At the moment, I am connected to a dummy server and that's not giving me the error that Eric described you guys were experiencing.
> > 
> > 
> > Rascal believes this issue appears with how we're parsing the event object. Currently we are using parseISO for the dates, when we should be using parseJSON. Tagging @RascalTwo for visibility.
> 
> @RascalTwo, @Caleb-Cohen and @intelagense how can I emulate this bug?

Good question. I was actually under the impression that all the dates were off by at least a few seconds, but when I changed `return format(isoDate, 'p') in the `formatToLocalTime` in`client/utilities/src/utilities` to `return format(isoDate, 'pp')` I'm not seeing the expected errors in seconds. 

*I'm not sure* how to reproduce this error.

<img width="149" alt="Screen Shot 2022-12-10 at 3 29 19 PM" src="https://user-images.githubusercontent.com/75268174/206875920-5dbb6df8-6480-4521-bf8a-effcf33a9440.png">

**Comment by JoeDravarol** [comment]
Wild guess:
I'm under the impression that, that one specific Mongo document/event that caused the ghost bug might had been an outdated document that was submitted through an old interation of the frontend form?

Probably best to archive this issue until the bug resurface again when 100Devs member uses the application.

**Comment by Caleb-Cohen** [comment]
Not reproducible closing now.
