### ISSUE TITLE
Fix Recurring Events Logic to the Event Object

### ISSUE THREAD

**Issue by Caleb-Cohen** [Caleb-Cohen/Together#148]
**Please provide a summary of the feature**
PR into feature/recurringEvents

Have events with recurring view in the calendar. 

**Are there any potential issues you foresee with this feature**

**Is this feature related to any current or past issues? Please provide the #**
this is a subset of #38  
**Additional context**

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by JoeDravarol** [comment]
Has this been completed? If not I'd like to work on it.

**Comment by Caleb-Cohen** [comment]
> Has this been completed? If not I'd like to work on it.

@intelagense is leading this up, but will need help.

**Comment by Caleb-Cohen** [comment]
Compelted
