### ISSUE TITLE
Update Add Event Form to match updated event model

### ISSUE THREAD

**Issue by Caleb-Cohen** [Caleb-Cohen/Together#152]
**Please provide a summary of the feature**
With the updates to the events model the event form can no longer submit objects in the feature/recurringEvents branch.

PR into feature/recurringEvents

**Are there any potential issues you foresee with this feature**
If you are accessing a database with older event objects your calendar may white screen and you should delete your event objects.

**Is this feature related to any current or past issues? Please provide the #**
#148 

*If you're interested in working on this feature, please comment so you can be assigned*
Assigned to @InstincDev

**Comment by InstincDev** [comment]
Thank for posting the issue.  It's all good 👍🏾. I wasn't planning on working on this till Saturday evening. I will check for updated details then.

**Comment by Caleb-Cohen** [comment]
Completed
