### ISSUE TITLE
Soft Security for Events

### ISSUE THREAD

**Issue by Caleb-Cohen** [Caleb-Cohen/Together#153]
**Please provide a summary of the feature**
Going to break these issues into multiple parts. People can claim specific sub-features.

- Prevent specific users from submitting more than 5 event objects into the database.

- Recurring events cannot be more than 3 months between start and end. Can either reject the input or stop the object from being submitted. assigned to @isaaclee12 

- Start dates cannot be in the past. Assigned to @WonjaeSung 

- Start or end dates can only exist for 2022/2023. No 2024+ or before 2022. Assigned to @WonjaeSung 

**Are there any potential issues you foresee with this feature**

**Is this feature related to any current or past issues? Please provide the #**

**Additional context**

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by WonjaeSung** [comment]
@Caleb-Cohen I can take this

**Comment by Caleb-Cohen** [comment]
> @Caleb-Cohen I can take this

Which ones? I have this broken into parts.

**Comment by WonjaeSung** [comment]
These two - 

Start dates cannot be in the past

Start or end dates can only exist for 2022/2023. No 2024+ or before 2022.

They pair up nicely.

**Comment by Caleb-Cohen** [comment]
> These two -
> 
> Start dates cannot be in the past
> 
> Start or end dates can only exist for 2022/2023. No 2024+ or before 2022.
> 
> They pair up nicely.

assigned!

**Comment by isaaclee12** [comment]
I can take "Recurring events cannot be more than 3 months between start and end. Can either reject the input or stop the object from being submitted". I have some basic ideas on how to do possibly this using React hooks and the like. I'm new to the project so I'll definitely have some questions about how the project's structure.

Also I'm aware that some new features are going to be merged back into the "development" branch very soon, specifically the form to add events. Should I wait until those are merged before beginning implementation?

**Comment by Caleb-Cohen** [comment]
> I can take "Recurring events cannot be more than 3 months between start and end. Can either reject the input or stop the object from being submitted".
> 
> I have some basic ideas on how to do possibly this using React hooks and the like.
> 
> Also I'm aware that some new features are going to be merged back into the "development" branch very soon, specifically the form to add events. Should I wait until those are merged before beginning implementation?

feature/formSecurity already has the features you speak of to add events. You should be able to fully test out security as is.

**Comment by DevRhyse** [comment]
Hey, I'd really love to help out on one of these if I could. Even to just hang out and try to learn something would be great!

**Comment by WonjaeSung** [comment]
@Caleb-Cohen, we have fixed these issues. It's ready to be merged!

**Comment by Caleb-Cohen** [comment]
> @Caleb-Cohen, we have fixed these issues. It's ready to be merged!

Merged what into where? I do not see an open PR.

**Comment by isaaclee12** [comment]
Quick update to end 2022:

- Our plan is to implement some tests that check each field's respective value in the FormContext individually
- "Errors" for each test will appear on the form in the client respective to each failed test
- Also we had merge errors at some point and it was a nightmare, but we pushed through them.
