### ISSUE TITLE
Events should be organized by time in the Calendar

### ISSUE THREAD

**Issue by Caleb-Cohen** [Caleb-Cohen/Together#172]
**Describe the bug**
Events appear to be sorted by the order in which they are entered and not by the time of the event
<img width="132" alt="Screen Shot 2022-12-14 at 11 10 22 AM" src="https://user-images.githubusercontent.com/75268174/207661606-7b8ad658-0b4c-4fe5-a5c0-8134ab138e1c.png">

**To Reproduce**
1. Go to ['Together'](https://together.cyclic.app/) or start the server in your development enviroment
2. Login with discord
3. Click on Navigate to Calendar Page

**Expected behavior**
Events should be sorted by earliest to latest event in a given day.

**Screenshots**
Included in body

*PR should go into development branch*

**Desktop (please complete the following information):**
Appears on all devices

**Comment by romanstetsyk** [comment]
I'll take this one
