### ISSUE TITLE
Event View Modal is not clickable when user is not logged in

### ISSUE THREAD

**Issue by Caleb-Cohen** [Caleb-Cohen/Together#174]
## Describe the bug
Clicking on an event should produce an event view modal to show more instructions, as provided in the screenshots.

Currently, the modal is not clickable if a user is not logged in.

## To Reproduce
1. Go to Together.Cyclic.App
2. Ensure you are logged out
3. Navigate to the calendar page
4. click any visible event

## Expected behavior
Users not-logged in should have access to the Event View Modal

## Screenshots
<img width="683" alt="Screen Shot 2022-12-14 at 12 16 53 PM" src="https://user-images.githubusercontent.com/75268174/207674763-97db51a2-5cb7-41dd-829e-ea3ef747b326.png">

## Which Branch should this fix be Pulled into?
PR into Development

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by MatthewBozin** [comment]
I'll take this on! ETA 5 mins
