### ISSUE TITLE
Login with Discord is taller than expected

### ISSUE THREAD

**Issue by Caleb-Cohen** [Caleb-Cohen/Together#175]
## Please provide a summary of the feature

Login with Discord looks a bit tall
<img width="305" alt="Screen Shot 2022-12-14 at 12 28 56 PM" src="https://user-images.githubusercontent.com/75268174/207679234-cc8b3917-3bd5-46f7-ade5-364645e90efe.png">

compared to the logout button
<img width="300" alt="Screen Shot 2022-12-14 at 12 29 42 PM" src="https://user-images.githubusercontent.com/75268174/207679473-25cf5397-8aa3-4e1d-85f9-66ac96a014e2.png">

## Which Branch should this fix be Pulled into?
PR into Development

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by TreLynnnn** [comment]
Alright, I’ll tackle this issue!

**Comment by Caleb-Cohen** [comment]
> Alright, I’ll tackle this issue!

All yours! I'll set the ETA as 12/19.
