### ISSUE TITLE
Redesign Calendar Page to Match Design

### ISSUE THREAD

**Issue by Caleb-Cohen** [Caleb-Cohen/Together#176]
## Please provide a summary of the feature

Currently, the calendar only has the calendar and none of the design elements associated with the design docs. This task is build the front end of the calendar page. 

![206335415-9b8ae4a7-806b-4771-a853-66a9f6789e40](https://user-images.githubusercontent.com/75268174/207681720-4bbc46ba-6309-4ab0-877e-4db43e4bf6b0.png)

## Which Branch should this fix be Pulled into?
PR into feature/CalendarPageRedesign

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by luciousmc** [comment]
I'd like to get in on this B)

**Comment by Caleb-Cohen** [comment]
> I'd like to get in on this B)

All yours. This is a decently big task. What type of ETA would you like to set?

**Comment by luciousmc** [comment]
> > I'd like to get in on this B)
> 
> All yours. This is a decently big task. What type of ETA would you like to set?

How does 12/21-12/23 sound? I am attending a wedding this weekend. Do you need it done sooner?

**Comment by Caleb-Cohen** [comment]
> > > I'd like to get in on this B)
> > 
> > 
> > All yours. This is a decently big task. What type of ETA would you like to set?
> 
> How does 12/21-12/23 sound? I am attending a wedding this weekend. Do you need it done sooner?

Nope that works great. We look forward to seeing it on 12/23!

**Comment by Caleb-Cohen** [comment]
@luciousmc feature/CalendarPageRedesign is ready for PR. I have also linked @HondaChan14 and @Natashka333 to help assist with the needed alterations.

**Comment by Natashka333** [comment]
Hi guys! I appreciate your ideas about the calendar page. I will try to send the mock-ups by the end of the day 😊

**Comment by Caleb-Cohen** [comment]
> Hi guys! I appreciate your ideas about the calendar page. I will try to send the mock-ups by the end of the day 😊

Thanks Natalie. Can you throw in a Feedback and Join the Team buttons into your next design?

**Comment by Natashka333** [comment]
> > Hi guys! I appreciate your ideas about the calendar page. I will try to send the mock-ups by the end of the day 😊
> 
> Thanks Natalie. Can you throw in a Feedback and Join the Team buttons into your next design?

Sure! Will do it.

**Comment by Natashka333** [comment]
![Together Calendar Page](https://user-images.githubusercontent.com/102708144/208223025-a6d3f73c-08d3-4392-b8cb-b57e7baa33d1.png)


Hi, team. 

I did the sidebar:

- It can be just icons. When you click on an icon, the wide sidebar pops up. 

- Or we can see the icons with their functions' names on the sidebar.


Also, I added some pictures on the left bottom corners. So, 'the people' can be different every month. 

Next, I changed the grey gaps on the calendar (first left option)  into white. I think I like white more. For me, it looks more balanced. 


Let me know what you think about redesigning, including functionality and colors.

**Comment by Caleb-Cohen** [comment]
@Natashka333 Looks great!

@luciousmc and @HondaChan14 here are my thoughts, but I'd love your input. Add the togglable nav bar to the left. Keep the original design that @luciousmc did, and setup a media query to only the togglable nav bar when it gets too small. 

If you feel that there is even the largest screens cannot fit the original design then I would just include the nav bar, but I feel like we're missing some more blue as a contrast. 

What are yall's thoughts?

**Comment by luciousmc** [comment]
Nice job @Natashka333 !

A few things I was thinking about...

1. Will the sidebar expand on hover like from Honda's project, or on click? Or another option is to have another icon that handles opening and closing it.
2. When the sidebar is expanded, I'm assuming the whole peachy area will expand and the calendar will shrink? Or would it just expand over the calendar?
3. Maybe the 'Add to Calendar' icon could be a plus sign or have one on it to be more obvious what it is while the sidebar is collapsed? Just a  thought, I know you can expand it to see the text.
4. Another thought, if the sidebar is toggleable we could have tooltips popup on hover showing the full text. This can also be an option for the events that get truncated.

What do ya'll think? @Natashka333 @HondaChan14 @Caleb-Cohen

**Comment by HondaChan14** [comment]
#1 I would say maybe a button for accessibility so people can know where the nav menu is at all times.

#2 hmmm would could have it maybe overlap the screen so that it doesn't disrupt the calendar to shrink when opening and collapsing  

#3 Yea thats sounds good to me to add the Plus Sign

#4 yea i like that idea

**Comment by Natashka333** [comment]
@HondaChan14, @Caleb-Cohen and @luciousmc , thanks for your feedbacks. I took your points and tried to play around in Figma. 

1. I change the background color to light blue. 
2. I put an expanded sidebar to check what it will look like. I also brought two ways of sections ( all icons in one section, or each icon is a separate section).
3. Another mockup includes a 'pancake' icon. Click on it and the expanded sidebar comes over the calendar.
4. (And if I understand your @luciousmc  forths point right), I tried to create the look of the icons when you guide the mouse to/click on one of them, and the expanded sidebar of that icon appears. 

Let me know, what you think. 


![Together Redesign 2](https://user-images.githubusercontent.com/102708144/208269653-5585e8db-2abd-4032-a000-4c64753f42c0.png)

**Comment by Caleb-Cohen** [comment]
<img width="263" alt="Screen Shot 2022-12-17 at 7 22 51 PM" src="https://user-images.githubusercontent.com/75268174/208272526-08722396-5990-4878-bac5-bbe622f024ac.png">
This one is my favorite thus far. The popout seems just a little off, though, and I can't quite put my finger on it. Maybe the popout starts a bit too far on the right?

The transparency is a nice touch.

**Comment by luciousmc** [comment]
I like the expanded sidebar with the full calendar next to it, but I'm also ok with it just expanding on top of it. I prefer the block of items over the separated one.

- I'm thinking the toggle icon could be a small arrow or something similar that changes direction based on the collapsed state of the sidebar.
- @Natashka333 what do you think about the tooltips just being a dark background with some white text that appear above the icon you're hovering?

Other than that I'll start working on this tonight. Honda has been under the weather and said I can start.

**Comment by Caleb-Cohen** [comment]
> I like the expanded sidebar with the full calendar next to it, but I'm also ok with it just expanding on top of it. I prefer the block of items over the separated one.

Can you include pictures of which ones you're referencing so I can better follow them? I'm open to this! We do not need to go with just what I like.

**Comment by Natashka333** [comment]
Merry Christmas, team!

Here I am attaching new mockups:

This one with the arrow to expand the bar and the arrow to reduce the size  (it will be only one button, I am just showing how it will look in both conditions). (as @luciousmc idea the arrow changes its direction based )

![Screen Shot 2022-12-25 at 8 55 01 AM](https://user-images.githubusercontent.com/102708144/209474587-89574e5a-b165-4201-85ac-d936ffdaa267.png)


And here is the other great point (thanks @luciousmc ). I added tooltips that appear above the icon.

![Screen Shot 2022-12-25 at 8 49 20 AM](https://user-images.githubusercontent.com/102708144/209474842-424cba7e-7994-40da-ac69-0e35e30874b1.png)




Feedbacks are welcome! 
Happy Holidays!
