### ISSUE TITLE
Style Navigation Buttons

### ISSUE THREAD

**Issue by MatthewBozin** [Caleb-Cohen/Together#178]
### Intro
This issue has been opened specifically to give 100Devs members a chance to get involved. The issues presented will have more instruction and be easier to solve. If you are already contributing to this project or your skills are well-ahead of this issue, consider letting someone else take this on!

## Summary
This issue is for someone who knows Tailwind, but is new to React and wants some hands-on experience working in a React environment.

### Creating your branch
- Navigate to the development branch using `git checkout development`.
- Create a new branch using `git branch -b style-navigation-buttons`.
- If you have questions, more instructions about this can be found in our [contributing document.](https://github.com/CalebCohen/Together/blob/development/.github/CONTRIBUTING.md)

### Setting up a local server
- Run `npm run dev-concurrent` in a vscode terminal.
- If you get errors, you may have to do one of the following:
- Delete your node_modules folder and then run `npm i`
- Make sure you have a .env file with the [necessary secrets](https://github.com/Caleb-Cohen/Together/wiki/02---Onboarding)

### What you need to do
Style the buttons!
- You can find the design documents at the bottom of [this discussion](https://github.com/Caleb-Cohen/Together/discussions/17). Following the design documents is encouraged.
- Make sure to put your Tailwind stylings in a 'className' property. React requires the Camel Case and will throw an error if you do 'class'.

### When you are done
-Use `git add .` and then `git commit -m 'add a descriptive commit message here'` to commit your changes to your local branch.
-Push your commit(s) using `git push`.
-Open your fork in github and you will see a message saying you can create a pull request. Make sure your pull request is pulling into the 'development' branch instead of 'main'.

### Who to contact
If you have any questions, you can either send a message in the Together channel in 100Devs Discord or DM `Saker Tarsos#7223`.

### Relevant file locations
You will find the components you need to style in: 
- `client/src/App.js` line 32
- `client/src/feature/home/LandingPage.js` line 11
- Here are the buttons in the UI as they currently stand:
![image](https://user-images.githubusercontent.com/111899522/207720668-b2e00e29-c567-47d2-876b-25c050b79c52.png)
![image](https://user-images.githubusercontent.com/111899522/207720782-2a1266b3-3772-463c-a30d-3cba4af9296b.png)

## Potential Problems
If you would like help placing the buttons in a different part of the page, ask `Saker Tarsos#7223` on Discord.

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by HondaChan14** [comment]
Hey! I'll take part in this :D

**Comment by Caleb-Cohen** [comment]
> Hey! I'll take part in this :D

Assigned
