### ISSUE TITLE
Make Current Day of the Month Stand Out

### ISSUE THREAD

**Issue by MatthewBozin** [Caleb-Cohen/Together#179]
## Please provide a summary of the feature
Add some styling that makes the current day of the month stand out from the rest in the calendar.
Relevant files: `client/src/features/calendar/DayCardList.js` and `client/src/features/calendar/DayCard.js`

## Are there any potential issues you foresee with this feature
No

## Is this feature related to any current or past issues? Please provide the #
No

## Which Branch should this fix be Pulled into?
PR into development

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by Caleb-Cohen** [comment]
Here's what I got so far. @natashka333 any comments on styling?

<img width="1225" alt="Screen Shot 2022-12-22 at 12 45 31 PM" src="https://user-images.githubusercontent.com/75268174/209214121-d705dfeb-d2db-4161-956e-cc407d1fb889.png">

**Comment by MatthewBozin** [comment]
This looks good to me. Once we get the functionality implemented, changing the color should be as easy as updating a single value!

**Comment by Caleb-Cohen** [comment]
> This looks good to me. Once we get the functionality implemented, changing the color should be as easy as updating a single value!

I have a PR open for review at #199

**Comment by Caleb-Cohen** [comment]
Merged to development. If there is any feedback regarding styling please open a new issue!
