### ISSUE TITLE
Include discordName with an event.

### ISSUE THREAD

**Issue by Caleb-Cohen** [Caleb-Cohen/Together#183]
## Please provide a summary of the feature

Add event author's name to the bottom of event view modal so that users can know which user created the event and have a contact if they have questions.

<img width="502" alt="Screen Shot 2022-12-15 at 11 20 43 AM" src="https://user-images.githubusercontent.com/75268174/207926300-8297f829-587d-4754-ab25-d786a492747b.png">

"Event Author: Caleb#9822"

## Are there any potential issues you foresee with this feature

The author is not stored in the date array of objects. It may be tricky accessing a level up to get to the discordName keyvalue.
![4557E4EB-3A2A-4E5A-B518-95CE802D2A75](https://user-images.githubusercontent.com/75268174/207927335-bae533cb-1a1d-4410-aca1-b25da922fb84.jpeg)

## Which Branch should this fix be Pulled into?
PR into Development

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by miguelbj** [comment]
I might have a solution for this. I made some fake data in Mongo and wrote some python scripts.
We could run either one, or both. 

**Solution:**
Having the `parent_id` helps us query that object and grab the `discordName`, or we can just put the `discordName` inside of each object in the `dates` array and grab it that way.


- **The first script adds the discord name into each array element:**
<img width="372" alt="image" src="https://user-images.githubusercontent.com/23278343/208031225-71683314-aa56-4195-ada6-30dfc918c4f1.png">


- **The second script get the `_id` from the parent object and sets it as a value in each array element as `parent_id`.**
<img width="438" alt="image" src="https://user-images.githubusercontent.com/23278343/208030941-89ec03f1-739a-4737-82bd-677490800121.png">

**Comment by romanstetsyk** [comment]
I can do this one
