### ISSUE TITLE
Overhaul/Update React Context with the SOLID approach

### ISSUE THREAD

**Issue by JoeDravarol** [Caleb-Cohen/Together#192]
## Please provide a summary of the feature

From my understanding a context eliminate issues in regards to props drilling, the states listed does not have this concern so they can be refactored to a regular state: **modal**, **event**, **page**

After removal of the state mentioned previously, I would'd like to propose we change our global context into a **User** or **Auth** Context where everything related to that context will live in a single file using the SOLID approach, which allows us to bring the Context into a "Single source of truth". Any creating, modyfying, deleting of the context will be inside the context file which makes it easier for all developer to see and modify if require, without having to track down which components the context is being modified at.

The intention of this change is to make all component only consume the context and its method and brings the application design closer to the Single Responsibility principles.

### Created a sandbox to demonstrate the idea
[Definitely not a terrible sandbox](https://codesandbox.io/s/stupefied-babycat-bsrchd)

## Are there any potential issues you foresee with this feature

Singular event modal details may not work after this refactor but depend on how the re-usuable modal component get created this may not be a concerned.

## Which Branch should this fix be Pulled into?
PR into [refactor/contexts] (Need to be created)

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by Caleb-Cohen** [comment]
This should be completed
