### ISSUE TITLE
January 2023 Visualize Bug

### ISSUE THREAD

**Issue by Caleb-Cohen** [Caleb-Cohen/Together#206]
## Describe the bug
Looks like if a month starts on Sunday and runs 30+ days then it'll get cut off at the bottom

## To Reproduce
1. Go to Together
2. Advance to January 2023
3. Scroll down to the bottom
4. See 30th and 31st day cut off

## Expected behavior
30th and 31st should be full sized.

## Screenshots
<img width="1053" alt="Screen Shot 2022-12-25 at 8 50 45 AM" src="https://user-images.githubusercontent.com/75268174/209474510-1eb9b157-97c9-43de-83fd-73656e9b6de9.png">

## Which Branch should this fix be Pulled into?
PR into Development

## Additional context
October 2023 has the same issue. 

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by romanstetsyk** [comment]
The grid is set up to have 5 rows by default. Another corner case is when February starts on Monday. In this case, there will be 4 rows.

**Comment by romanstetsyk** [comment]
I'll fix this tonight if no one is currently working on it
