### ISSUE TITLE
Event is displayed on the same date every year

### ISSUE THREAD

**Issue by romanstetsyk** [Caleb-Cohen/Together#207]
## Describe the bug

The event is added to the calendar on the same date each year. For example, a non-recurring event scheduled on Jan 10, 2023, is displayed yearly.

## To Reproduce
1. Add an event on any date
2. Open the calendar on the same date next year
4. See the event

## Expected behavior
The event should not repeat each year.

## Screenshots
<img width="815" alt="image" src="https://user-images.githubusercontent.com/25715951/209589528-8d901b6b-c04b-44cf-8c6f-593c68361132.png">
<img width="888" alt="image" src="https://user-images.githubusercontent.com/25715951/209589539-a1c8e901-e159-4801-a1de-839e939bb3e0.png">
<img width="356" alt="image" src="https://user-images.githubusercontent.com/25715951/209589557-8dd2a058-7d8f-47ad-9a03-224eae7b136c.png">

## Which Branch should this fix be Pulled into?
PR into development

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by Caleb-Cohen** [comment]
I made a PR in #209, would you mind reviewing it?

**Comment by romanstetsyk** [comment]
Looks good to me! That's exactly what I came up with.

**Comment by isaaclee12** [comment]
I also happened to be looking at the issue for a moment, the solution you came up with was something I was going to try out. I did just copy and paste the code you wrote and I can confirm it works on my machine :)
