### ISSUE TITLE
Update Event Schema and Event Model

### ISSUE THREAD

**Issue by Caleb-Cohen** [Caleb-Cohen/Together#215]
## Please provide a summary of the feature

We've had extensive [discussions](https://github.com/Caleb-Cohen/Together/discussions/181) about editing the event model to accomplish the necessary tasks more efficiently. 

We've settled on option #3 of what @miguelbj has proposed. Please review his comments for a complete understanding.

This includes: 
- All events will be a separate date object. This includes recurring dates, as they will no longer be stored into a recurring dates array.
- Date objects will have a groupID. This allows recurring events to be grouped together under one type of event.

## Are there any potential issues you foresee with this feature

This is a pretty big update as this is a big change, and this will break a fair bit of logic in how Together fundamentally works. This should be a solo issue.

## Which Branch should this fix be Pulled into?
PR into eventModalUpdate

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by intelagense** [comment]
@romanstetsyk 👋

**Comment by romanstetsyk** [comment]
Is there a separate branch for this issue?

**Comment by Caleb-Cohen** [comment]
> Is there a separate branch for this issue?

Trying to finish a few PRs before I branch this one. Give me until the end of the day.

**Comment by Caleb-Cohen** [comment]
> Is there a separate branch for this issue?

@romanstetsyk I'm still out with the family. If you have any work done before heading to bed PR to development and I will create and switch to the new branch.

**Comment by miguelbj** [comment]
Hey @Caleb-Cohen is there a plan in place to unwind and then delete the old nested objects in the `dates`  array? Or is the project Together small enough to delete and remake the events that are currently in there so they match the new data model?

**Comment by Caleb-Cohen** [comment]
> Hey @Caleb-Cohen is there a plan in place to unwind and then delete the old nested objects in the `dates` array? Or is the project Together small enough to delete and remake the events that are currently in there so they match the new data model?

Delete and replace. We're currently adding event objects on a month-to-month basis, and a vast majority of January events are not even in the DB yet.
