### ISSUE TITLE
Create User Schema

### ISSUE THREAD

**Issue by Caleb-Cohen** [Caleb-Cohen/Together#22]
Creating an issue for creating user schema.

**Comment by Caleb-Cohen** [comment]
@yuhwaa doesn't look like I can assign you.

**Comment by yuhwaa** [comment]
@Caleb-Cohen thanks for opening the issue — I think you should be able to assign it after this comment.

**Comment by Caleb-Cohen** [comment]
Perfect @yuhwaa it's all yours!

**Comment by yuhwaa** [comment]
Thank you! Noting discussion #9 for reference.

**Comment by yuhwaa** [comment]
User Schema updated at #23

**Comment by Caleb-Cohen** [comment]
Thank you! @yuhwaa

**Comment by yuhwaa** [comment]
🙏🏻
