### ISSUE TITLE
Cleanup: Remove test ping function

### ISSUE THREAD

**Issue by timmyichen** [Caleb-Cohen/Together#232]
### Intro
This issue has been opened specifically to give 100Devs members a chance to get involved. The issues presented will have more instruction and be easier to solve. If you are already contributing to this project or your skills are well-ahead of this issue, consider letting someone else take this on!

## Summary
There was a `ping` controller test method when the project started, but is no longer used.  It can be removed with no detriment to the product.

## The Task

Remove all references to the `ping` controller test method and wherever it's called.  All instances can be found [here](https://github.com/Caleb-Cohen/Together/search?q=ping).

### Creating your branch
- Fork the Together repository.
- Navigate to the development branch using `git checkout development`.
- Create a new branch using `git branch -b your-branch-name-here`.
- If you have questions, more instructions about this can be found in our [contributing document.](https://github.com/CalebCohen/Together/blob/development/.github/CONTRIBUTING.md)

### Setting up a local server
- Execute `npm install`
- Execute `npm run dev-concurrent` in a vscode terminal.
- If you get errors, you may have to do one of the following:
- Delete your node_modules folder and then run `npm i`
- Make sure you have a .env file with the [necessary secrets](https://github.com/Caleb-Cohen/Together/wiki/02---Onboarding)

### What you need to do
(Describe the tasks needed to complete the issue here. Try to describe them in detail and provide context.)

### When you are done
-Use `git add .` and then `git commit -m 'add a descriptive commit message here'` to commit your changes to your local branch.
-Push your commit(s) using `git push`.
-Open your fork in github and you will see a message saying you can create a pull request. Make sure your pull request is pulling into the 'development' branch instead of 'main'.

### Who to contact
If you have any questions, you can either send a message in the Together channel in 100Devs Discord.

### Relevant file locations
See [link](https://github.com/Caleb-Cohen/Together/search?q=ping)

## Potential Problems
N/A

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by ChrisMunozCodes** [comment]
Hello, I'm interested in working on this issue!
