### ISSUE TITLE
Need Tighter Back-End Data Validation

### ISSUE THREAD

**Issue by isaaclee12** [Caleb-Cohen/Together#233]
# IMPORTANT: This issue should not be worked on before the new schema/data object model(s) to be merged into development.

## Please provide a summary of the feature

Credit to @timmyichen for helping me understand this issue.

The back end needs tighter data validation/sanitization. Currently, Mongoose does well to whitelist the data to ensure that it fits the MongoDB object model:

``` server\controllers\events.js

      await Event.create({
        title: data.title,
        description: data.description,
        initialDate: data.initialDate,
        finalDate: data.finalDate,
        startTime: data.startTime,
        endTime: data.endTime,
        recurring: data.recurring.rate === "weekly",
        dates: data.dates,
        recurringPattern: data.recurring,
        location: data.location,
        discordName: req.user.displayName,
      });
```

- ```server\models\Event.js``` could also use some bounds for data, e.g. mins and maxes for String fields to prevent DDOS attacks via very large strings (Docs for this: https://mongoosejs.com/docs/validation.html).
- Most of the logic in the generateRecurringDatesArray() in ```client\src\utilities\calendar.js``` should be moved to the backend
- The "5 events per user" check from issue #153 can also be transferred here.

## Are there any potential issues you foresee with this feature
- There will be quite a bit of code that will be refactored on both the frontend and backend for this issue. Communication will be key to preventing merge errors with other issue-branches.

## Is this feature related to any current or past issues? Please provide the #
- Some overlap with Issue #153 Soft Security

## Which Branch should this fix be Pulled into?
PR into development

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by romanstetsyk** [comment]
I would love to work on this issue

**Comment by romanstetsyk** [comment]
@isaaclee12, what do you think are the reasonable max lengths for strings in the context of this app?

**Comment by Caleb-Cohen** [comment]
> @isaaclee12, what do you think are the reasonable max lengths for strings in the context of this app?

Twitter max character limit is 280. Think around there would be a good starting point?

**Comment by isaaclee12** [comment]
> @isaaclee12 Could you elaborate on the benefits of moving logic from the `generateRecurringDatesArray` method to the backend?

Hey Roman, sorry for the late response. Moving whatever logic we can to the back-end is best practice because code in the back-end (which the user can't directly manipulate) is infinitely more secure than code in the front-end (which the user can manipulate). 

> @isaaclee12, what do you think are the reasonable max lengths for strings in the context of this app?
I liked Caleb's idea for a limit of 280 characters for the descriptions. Maybe make the limit for title and location something shorter, say 50 to 100 characters.
