### ISSUE TITLE
Re-render Calendar When Event is Submitted

### ISSUE THREAD

**Issue by MatthewBozin** [Caleb-Cohen/Together#235]
## Please provide a summary of the feature

Currently, when a user submits an event using the Add Event Form, they must navigate to the landing page and back in order to see their created event on the calendar.

Make it so that when a user submits an event using the Add Event Form, Together re-renders Calendar.js, allowing Calendar.js to make a new getAll() request to the server, which should include the newly added event.

## Is this feature related to any current or past issues? Please provide the #
No

## Which Branch should this fix be Pulled into?
PR into development

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by timmyichen** [comment]
@Caleb-Cohen I can take this on tomorrow during the demo if that's cool

**Comment by Caleb-Cohen** [comment]
> @Caleb-Cohen I can take this on tomorrow during the demo if that's cool

all yours!
