### ISSUE TITLE
Redirect user to Calendar when user logs in

### ISSUE THREAD

**Issue by Caleb-Cohen** [Caleb-Cohen/Together#239]
## Please provide a summary of the feature

Currently, login redirect the user back to the landing page. This feature should cause the user to see the calendar upon successful login. 

## Which Branch should this fix be Pulled into?
PR into Development

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by MatthewBozin** [comment]
Replaced with Good-100Devs-First-Issue version #268
