### ISSUE TITLE
Add content to the feature/landingPageRedesign branch

### ISSUE THREAD

**Issue by Caleb-Cohen** [Caleb-Cohen/Together#249]
## Please provide a summary of the feature
Landing page is missing content in the bottom boxes in the `feature/landingPageRedesign` branch.

Some things that couple be included.
- Info about 100Devs
- Description of the Together being open-source and a link to the github
- Meet the team
- Maybe a link to https://communitytaught.org/resources/

## Additional context
<img width="1069" alt="Screenshot 2023-01-11 at 9 18 55 PM" src="https://user-images.githubusercontent.com/75268174/211967907-04b6563b-e814-45c1-b7a2-5147b5f3bc17.png">

## Which Branch should this fix be Pulled into?
PR into feature/landingPageRedesign

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by timmyichen** [comment]
I imagine the text itself will go through some wordsmithing / have several drafts.  Updating text in a react project is a lot harder than updating text in, say, a Google Doc - so I think it would be best if we hammered out the text to add _before_ someone picks this up.

**Comment by AitchGrasso** [comment]
Hello! I would like to help with this issue and help write out the content for the landing page.

**Comment by HondaChan14** [comment]
Hey ill also be over seeing this issue as well 😃

**Comment by Caleb-Cohen** [comment]
> Hello! I would like to help with this issue and help write out the content for the landing page.

Perfect! In the meeting we discussed. 

Box 1: Talk about 100Devs and how to join.
Box 2: Talks about how we have videos on how to use and contribute to Together. Should probably mention the videos are a work in progress.
Box 3: Talk about community taught and link to the resources

Bottom Box: Talk about the Together Team.

Can you respond back with the content when it's created? I'd like to have some time to provide some feedback prior to @HondaChan14 or you spending time developing it.

**Comment by HondaChan14** [comment]
Hey Yes will do!

**Comment by AitchGrasso** [comment]
Thank you, @Caleb-Cohen.

**Box 1:** 100Devs and how to join.

100Devs (https://leonnoel.com/100devs/) is a diverse and inclusive community of participants in a software engineering training program run by Leon Noel. It is 100% free and requires absolutely no previous technical experience. 

Get started by joining us on Discord (discord link)

(Include catchup crew info?)

**Box 2:** Talks about how we have videos on how to use and contribute to Together. Should probably mention the videos are a work in progress.

Would you like to contribute to Together?
Follow (along? on) our team* (our repo? on something? On Github?) for (coming soon) our video series on how to use and contribute to Together, together

**Box 3**: Talk about community taught and link to the resources

Keep track of your 100devs course progress using CommunityTaught.org created by 100devs alumni (alumnae) Laura Abro. 
Additional 100devs resources (link: https://communitytaught.org/resources/)

**Last box**: about the team
Together is a community-driven open source project backed by 100devs students led by (include names of maintainers). Together is not only designed to be a valuable tool to the 100devs community but also provides an additional opportunity for students to learn in a group environment. Together is open to all varying skill sets and encourages peer programming. Interested in collaborating with us? (link to onboarding guide) (discord channel link?)

**Comment by Caleb-Cohen** [comment]
What are your thoughts?

Box 1: I like it - what about this slight change? 

100Devs (https://leonnoel.com/100devs/) is a diverse and inclusive community of participants in a software engineering agency and training program run by Leon Noel. It is 100% free and requires absolutely no previous technical experience.

Box 2:

We are currently working on video resources for individuals that would like to learn more about how to contribute to Together and how Together works. Follow along on our Youtube when it is ready!

Box 3: 

Looks good! It would be Alumna in this case.

ast Box - Looks great! I think it should link to the github contributing documents or Onboarding on the wiki not discord.

**Comment by AitchGrasso** [comment]
That's perfect, thank you @Caleb-Cohen. @HondaChan14, final text: 

Box 1: 
100Devs (https://leonnoel.com/100devs/) is a diverse and inclusive community of participants in a software engineering agency and training program run by Leon Noel. It is 100% free and requires absolutely no previous technical experience.

Box 2: 
We are currently working on video resources for individuals that would like to learn more about how to contribute to Together and how Together works. Follow along on our Youtube when it is ready!

Box 3: 
Keep track of your 100devs course progress using CommunityTaught.org created by 100devs alumna, Laura Abro.
Additional 100devs resources (link: https://communitytaught.org/resources/)

Last box: Together is a community-driven open source project backed by 100devs students led by (include names of maintainers). Together is not only designed to be a valuable tool to the 100devs community but also provides an additional opportunity for students to learn in a group environment. Together is open to all varying skill sets and encourages peer programming. Interested in collaborating with us? (link to github contributing documents/onboarding guide)
