### ISSUE TITLE
Clicking "New Event" after event submission routes you back to landing page

### ISSUE THREAD

**Issue by timmyichen** [Caleb-Cohen/Together#251]
## Describe the bug
Our button to [create a new event after submitting a new one](https://github.com/Caleb-Cohen/Together/blob/18792905d33909af03ece7f371cb69b3c1ae448c/client/src/features/form/FormSuccess.js#L10-L14) is wrapped in an anchor tag with an href to the landing page (`/`)

## To Reproduce
1. Go through the event creation form
2. Submit it
3. Click on "New Event"
4. You'll be on the landing page

## Expected behavior
Ideally we would just reset the form state instead (and go back to step 1)

## Which Branch should this fix be Pulled into?
`development`

**Comment by MatthewBozin** [comment]
Remade into a 100Devs first try issue: #269

**Comment by Caleb-Cohen** [comment]
Didn't Tim fix this with #252

**Comment by timmyichen** [comment]
I did not - we just discovered it there
