### ISSUE TITLE
Redirect user to Calendar when user logs in 

### ISSUE THREAD

**Issue by MatthewBozin** [Caleb-Cohen/Together#268]
### Intro
This issue has been opened specifically to give 100Devs members a chance to get involved. The issues presented will have more instruction and be easier to solve. If you are already contributing to this project or your skills are well-ahead of this issue, consider letting someone else take this on!

## Summary

Currently, logging in redirects the user back to the landing page. This feature should cause the user to see the calendar upon successful login.

### Creating your branch
- Fork the Together repository.
- Navigate to the development branch using `git checkout development`.
- Create a new branch using `git branch -b your-branch-name-here`.
- If you have questions, more instructions about this can be found in our [contributing document.](https://github.com/CalebCohen/Together/blob/development/.github/CONTRIBUTING.md)

### Setting up a local server
- Execute `npm install`
- Execute `npm run dev-concurrent` in a vscode terminal.
- If you get errors, you may have to do one of the following:
- Delete your node_modules folder and then run `npm i`
- Make sure you have a .env file with the [necessary secrets](https://github.com/Caleb-Cohen/Together/wiki/02---Onboarding)

### What you need to do
We currently have a React Context called RoutingContext that controls which page is currently displayed.
Modify the code of LoginWithDiscord.js so that clicking on the "login" button will change the state variable in useRoutingContext from "landingPage" to "calendarPage" (changing that variable will redirect the user to the landing page).

### When you are done
-Use `git add .` and then `git commit -m 'add a descriptive commit message here'` to commit your changes to your local branch.
-Push your commit(s) using `git push`.
-Open your fork in github and you will see a message saying you can create a pull request. Make sure your pull request is pulling into the 'development' branch instead of 'main'.

### Who to contact
If you have any questions, you can either send a message in the Together channel in 100Devs Discord or contact  @MatthewBozin.

### Relevant file locations
client/src/contexts/RoutingContext/useProvideRouting.js
client/src/features/auth/LoginWithDiscord.js

## Potential Problems

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by jalonghurst** [comment]
Hi, I would love to work on this issue if possible!

**Comment by Caleb-Cohen** [comment]
> Hi, I would love to work on this issue if possible!

All yours!
