### ISSUE TITLE
Clicking "New Event" after event submission routes you back to landing page

### ISSUE THREAD

**Issue by MatthewBozin** [Caleb-Cohen/Together#269]
### Intro
This issue has been opened specifically to give 100Devs members a chance to get involved. The issues presented will have more instruction and be easier to solve. If you are already contributing to this project or your skills are well-ahead of this issue, consider letting someone else take this on!

## Summary
Our button to [create a new event after submitting a new one](https://github.com/Caleb-Cohen/Together/blob/18792905d33909af03ece7f371cb69b3c1ae448c/client/src/features/form/FormSuccess.js#L10-L14) is wrapped in an anchor tag with an href to the landing page (/)

###To Reproduce

1. Go through the event creation form
2. Submit it
3. Click on "New Event"
4. You'll be on the landing page

### Creating your branch
- Fork the Together repository.
- Navigate to the development branch using `git checkout development`.
- Create a new branch using `git checkout -b your-branch-name-here`.
- If you have questions, more instructions about this can be found in our [contributing document.](https://github.com/CalebCohen/Together/blob/development/.github/CONTRIBUTING.md)

### Setting up a local server
- Execute `npm install`
- Execute `npm run dev-concurrent` in a vscode terminal.
- If you get errors, you may have to do one of the following:
- Delete your node_modules folder and then run `npm i`
- Make sure you have a .env file with the [necessary secrets](https://github.com/Caleb-Cohen/Together/wiki/02---Onboarding)

### What you need to do
Remove the anchor element surrounding the "New Event" button. Modify the css of the elements so that the page visually remains the same. (Or a janky solution would just be to turn the anchor tag into a div with the exact same css classes.)

### When you are done
-Use `git add .` and then `git commit -m 'add a descriptive commit message here'` to commit your changes to your local branch.
-Push your commit(s) using `git push`.
-Open your fork in github and you will see a message saying you can create a pull request. Make sure your pull request is pulling into the 'development' branch instead of 'main'.

### Who to contact
If you have any questions, you can either send a message in the Together channel in 100Devs Discord or contact @MatthewBozin.

### Relevant file locations
client/src/features/form/FormSuccess.js

## Potential Problems

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by MatthewBozin** [comment]
Remade #251 as a 100Devs first try issue.

**Comment by mjbramich** [comment]
Hey, i'd like to help with this issue.
