### ISSUE TITLE
Fix browser console warning (class -> className)

### ISSUE THREAD

**Issue by romanstetsyk** [Caleb-Cohen/Together#276]
### Intro
This issue has been opened specifically to give 100Devs members a chance to get involved. The issues presented will have more instruction and be easier to solve. If you are already contributing to this project or your skills are well-ahead of this issue, consider letting someone else take this on!

## Summary

Invalid DOM property `class`.

<img width="598" alt="image" src="https://user-images.githubusercontent.com/25715951/213776280-6f7a9b2a-07e9-48fb-8660-3b23886e4ac3.png">

### Creating your branch
- Fork the Together repository.
- Navigate to the development branch using `git checkout development`.
- Create a new branch using `git checkout -b your-branch-name-here`.
- If you have questions, more instructions about this can be found in our [contributing document.](https://github.com/CalebCohen/Together/blob/development/.github/CONTRIBUTING.md)

### Setting up a local server
- Execute `npm install`
- Execute `npm run dev-concurrent` in a vscode terminal.
- If you get errors, you may have to do one of the following:
- Delete your node_modules folder and then run `npm i`
- Make sure you have a .env file with the [necessary secrets](https://github.com/Caleb-Cohen/Together/wiki/02---Onboarding)

### What you need to do
Search and replace `class=` with `className=`. There are 4 files that should be changed. [More about this](https://reactjs.org/docs/faq-styling.html#how-do-i-add-css-classes-to-components)

### When you are done
-Use `git add .` and then `git commit -m 'add a descriptive commit message here'` to commit your changes to your local branch.
-Push your commit(s) using `git push`.
-Open your fork in github and you will see a message saying you can create a pull request. Make sure your pull request is pulling into the 'development' branch instead of 'main'.

### Who to contact
If you have any questions, you can either send a message in the Together channel in 100Devs Discord or contact (put your name or contact info here).

### Relevant file locations

[File 1](https://github.com/Caleb-Cohen/Together/blob/580eaa942ed0090493f1fce8b0eea45d17bfa5c0/client/src/features/form/FormCreateEvent.js)
[File 2](https://github.com/Caleb-Cohen/Together/blob/580eaa942ed0090493f1fce8b0eea45d17bfa5c0/client/src/features/form/FormScheduleEvent.js)
[File 3](https://github.com/Caleb-Cohen/Together/blob/580eaa942ed0090493f1fce8b0eea45d17bfa5c0/client/src/features/home/LogoContainer.js)
[File 4](https://github.com/Caleb-Cohen/Together/blob/580eaa942ed0090493f1fce8b0eea45d17bfa5c0/client/src/features/home/NavButtons.js)

## Potential Problems
(List any problems the new developer could run into.)

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by timtom619** [comment]
Hi there! I just went through the onboarding and was looking to see if I can tackle this issue?
