### ISSUE TITLE
Conversion of local time to UTC on event submission causes weekly recurring events to be off by one day (in a very specific edge case)

### ISSUE THREAD

**Issue by isaaclee12** [Caleb-Cohen/Together#300]
## Describe the bug
A wild edge case has appeared!

Whenever you submit a weekly recurring event that is the current date in your time, but becomes the next date in UTC time, AND recurs on a day of week that is one day after the day you submit the event, the database saves your events on the wrong days of the week.

For example, if it's Wednesday, and you submit an event that recurs on Thursdays, and the start time of the event crosses the date threshold when the submitted times are converted to UTC timestamps, the date is offset by 1, but the submitted days of the week are not.

The suggested solution is to turn the days of week to ISO days of week, e.g. the integers 1,2,3,4,5,6,7 which represent Monday, Tuesday, ..., Sunday respectively, and then offset those numbers by 1 whenever we detect a date offset when we convert submitted datetimes to UTC.

Better to try to reproduce it yourself than explain it via text:
## To Reproduce
1. Run the application
2. Create a new event in the form with any title, description, and location
3. Set the event to recur "Weekly". Set the event to recur on whatever day tomorrow is. For better visualization of the bug, select other days of the week as well.
    a. For example, if today is Thursday, create an event that recurs weekly on Friday, Monday, and Wednesday.
4. Set the Start Date of the event to today
5. Set the Start Time of the event to whatever time in your current timezone is equivalent to midnight aka 00:00 in UTC (Use this tool to find your converted time: https://www.worldtimebuddy.com)
    a. For example, I am in EST. 7:00PM EST is equal to 0:00 UTC, so I will use 7:00PM as my Start Time.
6. Set the End Date to some date that's at least a week or two after the Start Date
7. Set the End Time to be an hour or so after the Start Time

Here's an example of what I put in today, Thursday 01/26/2023:
![image](https://user-images.githubusercontent.com/59675296/214998664-70410f21-6e83-4a58-93ed-60aba699fd82.png)

## Expected behavior
The submitted event should appear on every weekday as selected.

## Which Branch should this fix be Pulled into?
PR into development(???)

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by isaaclee12** [comment]
Roman appears to be working on this issue in PR #298.
I am also working on this in my own branch.
I will be in touch with Roman about working on this.

**Comment by isaaclee12** [comment]
Roman's PR #298 appears to have resolved the issue.

Unrelated, for records purposes, here are the tests I performed to reproduce the bug initially:

      Test 1: Start time at UTC Threshold
      - Below code untouched
      - Today is Fri, 1/27
      - Weekly recurring event on Sat/Sun/Mon
      - Date = 1/27/23 - 2/22-23
      - Time = 7pm-8pm ==> 0am-1am UTC
      - RESULT: Event recurs on Sun/Mon/Tues starting on Sun 1/29 from 7pm-8pm
      - Unexpected Behavior

      Test 2: Start time past UTC Threshold
      - Below code untouched
      - Today is Fri, 1/27
      - Weekly recurring event on Sat/Sun/Mon
      - Date = 1/27/23 - 2/22-23
      - Time = 10pm-11pm EST ==> 3am-4am UTC
      - RESULT: Event recurs on Sun/Mon/Tues starting on Sun 1/29 from 10pm-11pm
      - Unexpected Behavior

      Test 3: Both times before UTC Threshold
      - Below code untouched
      - Today is Fri, 1/27
      - Weekly recurring event on Sat/Sun/Mon
      - Date = 1/27/23 - 2/22-23
      - Time = 5pm-6pm EST ==> 10pm-11pm UTC
      - RESULT: Event recurs on Sat/Sun/Mon starting on Sat 1/28 from 5pm-6pm
      - Expected Behavior

      Test 4: Times before & after UTC Threshold
      - Below code untouched
      - Today is Fri, 1/27
      - Weekly recurring event on Sat/Sun/Mon
      - Date = 1/27/23 - 2/22-23
      - Time = 6:30pm-7:30pm EST ==> 11:30pm-0:30am UTC
      - RESULT: Event recurs on ASDFASDFSDAF starting on ASDFASDF from ASDFASDF
      - Expected Behavior

**Comment by Caleb-Cohen** [comment]
@isaaclee12 can I close this because of #298 merged?

**Comment by isaaclee12** [comment]
> @isaaclee12 can I close this because of #298 merged?

Yes :)
