### ISSUE TITLE
Plus sign should load start date of day clicked into form

### ISSUE THREAD

**Issue by isaaclee12** [Caleb-Cohen/Together#304]
## Please provide a summary of the feature
Currently, clicking the "plus" button on a date brings up an empty add event form. Given that there is a "plus" button for every date, it'd be intuitive for the start date (and perhaps also the end date) to be set to the respective date when clicked.

This could probably be implemented by fiddling with the dates and the FormContext.

## Are there any potential issues you foresee with this feature
No merge issues pleeease.

## Which Branch should this fix be Pulled into?
PR into development

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by DevRhyse** [comment]
I'd like to help out on this issue please :D

**Comment by intelagense** [comment]
Here is part of the mystery.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#value

**Comment by AitchGrasso** [comment]
Hey hey! I would like to work on this with @DevRhyse please!
