### ISSUE TITLE
Time zone: make it obvious

### ISSUE THREAD

**Issue by jsalaski** [Caleb-Cohen/Together#308]
Having just started using Together, I would suggest making it obvious which time zone the events are taking place. While I understand the events are synched to your current time zone, making that transparent would be helpful from a UI perspective.

**Comment by intelagense** [comment]
Someone else mentioned that recently as well. 
That would be pretty easy to add to the "add event" modal and "event details" modal.
Might be a little harder to indicate on the main calendar view (if that is even desired.)

**Comment by Caleb-Cohen** [comment]
Thanks for the feedback! I have opened #309 to solve this issue. Thank you!
