### ISSUE TITLE
Add timezones to time so that users will know the times are localized

### ISSUE THREAD

**Issue by Caleb-Cohen** [Caleb-Cohen/Together#309]
## Please provide a summary of the feature

Some users have reasonably assumed that the times within Together are synced to Easter Standard Time, because that is the time that Leon uses for 100Devs. This is incorrect for Together because we localize the time to the client. 

Including the client's timezone within the event view modal will help users understand that the time they are being shown is localized to their time. Please refer to this beautiful design mockup by @intelagense as an example. 

![image](https://user-images.githubusercontent.com/75268174/215948466-effe3a2f-f803-4ae7-8931-2677717e54f2.png)

Task: 
- Detect what timezone the user is in
- Report that timezone next to the event start and end time in [abbreviation format](https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations) 

## Are there any potential issues you foresee with this feature
If the client doesn't report a timezone but the local time it may be complicated to impossible to get the actual timezone abbreviation, and we may have to provide the UTC offset instead.

## Is this feature related to any current or past issues? Please provide the #
#308 

## Which Branch should this fix be Pulled into?
PR into development

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by intelagense** [comment]
This should also include the user's local time zone being indicated on the "add event" modal. 
Here is one idea for implementation:
![Event creation form screenshot with local timezones crudely appended to input labels using MSPaint](https://user-images.githubusercontent.com/18331781/216061226-a117ebf6-e7fa-472c-81c8-564dc900a05e.png)

**Comment by romanstetsyk** [comment]
This is an excellent idea but a bit tricky. What if the event starts after the time is switched to daylight saving time, e.g. CST -> CDT?
The easiest implementation would be something like what's on the screenshot. [Intl API](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Intl) provides a way to access users' timezone in a different format than abbreviations. What do you think?
<img width="538" alt="image" src="https://user-images.githubusercontent.com/25715951/216152973-1d252b1a-3073-447f-af7f-94f1e1a1f58a.png">

**Comment by intelagense** [comment]
> This is an excellent idea but a bit tricky. What if the event starts after the time is switched to daylight saving time, e.g. CST -> CDT?
> 
> The easiest implementation would be something like what's on the screenshot. [Intl API](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Intl) provides a way to access users' timezone in a different format than abbreviations. What do you think?
> 
> <img width="538" alt="image" src="https://user-images.githubusercontent.com/25715951/216152973-1d252b1a-3073-447f-af7f-94f1e1a1f58a.png">
> 
> 

Great idea! I highly prefer this sort of solution over the initial one I suggested 👍

**Comment by romanstetsyk** [comment]
Cool, I'll do this tonight
