### ISSUE TITLE
Implement Front-End Test Suite

### ISSUE THREAD

**Issue by MatthewBozin** [Caleb-Cohen/Together#314]
## Please provide a summary of the feature
Create a test suite using Jest/Cypress that tests front-end components and features. 
Test suite does not have to cover all components/use cases, but should be able to be extended in the future.
Bonus points: implement Github Actions workflow to run test suite on PR.

## Is this feature related to any current or past issues? Please provide the #
Backend test suite is being developed in #288. These are not dependent on each other, but eventually a 'test' script can be created to run both in sequence.

## Which Branch should this fix be Pulled into?
PR into development

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by Caleb-Cohen** [comment]
@RascalTwo this is high priority I expect this on my desk by midnight.

**Comment by luciousmc** [comment]
Hi @RascalTwo I'd like to tag along whenever you decide to do this B)
