### ISSUE TITLE
Visualize Event Objects for Corresponding Days

### ISSUE THREAD

**Issue by Caleb-Cohen** [Caleb-Cohen/Together#38]
Placeholder for discussion

**Comment by JoeDravarol** [comment]
I like to take on this issue.

**Comment by Caleb-Cohen** [comment]
@code2244 please comment so I can assign as well.

**Comment by code2244** [comment]
Hi I will like to help in this issue.

**Comment by code2244** [comment]
I'm available in the weekend too.

**Comment by Caleb-Cohen** [comment]
@code2244 @JoeDravarol We doing this tomorrow?

**Comment by code2244** [comment]
Yes, I will be at discord after 2pm possibly all day

**Comment by JoeSangine** [comment]
hello
