### ISSUE TITLE
Import calendar into views

### ISSUE THREAD

**Issue by JoeDravarol** [Caleb-Cohen/Together#5]
![image](https://user-images.githubusercontent.com/48932159/200141240-b63183d2-0739-494b-8715-c27961e8663f.png)

# Task
* Convert the [codepen](https://codepen.io/robstinson/pen/BaKOZry) template provided to React components

## Questions
* Should it be a static UI at the current stage or are there any dummy data to populate the each day to show the events?
* Should the view folder be replaced with React (create-react-app) or add **client** folder dedicated for React?

**Comment by JoeDravarol** [comment]
As per discussed on Discord for the task on this issue: 

> Just create a way to navigate to the calendar and make the calendar viewable.

I would like to be assigned this issue.

**Comment by Caleb-Cohen** [comment]
@JoeDravarol foe the design. Are you building it yourself or are you using the template provided in the link?

**Comment by JoeDravarol** [comment]
> 

I would be using the codepen template you provided.
If that's okay can I start working on this issue?

**Comment by Caleb-Cohen** [comment]
Yes that works!

Sent from my iPhone

On Nov 5, 2022, at 6:13 PM, Joe Lee ***@***.***> wrote:

﻿

I would be using the codepen template you provided.
If that's okay can I start working on this issue?

**Comment by intelagense** [comment]
Got you assigned @JoeDravarol 👍

**Comment by JoeDravarol** [comment]
![image](https://user-images.githubusercontent.com/48932159/200149920-c34640c3-c8cd-4ad0-a5e5-d34843d8a57c.png)

@Caleb-Cohen I have managed to convert the codepen template into React components. (Screenshot provided above)

Right now there is no functionality, it's all static. Is there anything else you would like me to add/do for this issue?

**Comment by Caleb-Cohen** [comment]
No. This task is completed we’ll add interactivity to the task list. Great work!

Sent from my iPhone

On Nov 5, 2022, at 8:39 PM, Joe Lee ***@***.***> wrote:

﻿

[image]<https://user-images.githubusercontent.com/48932159/200149920-c34640c3-c8cd-4ad0-a5e5-d34843d8a57c.png>

@Caleb-Cohen<https://github.com/Caleb-Cohen> I have managed to convert the codepen template into React components. (Screenshot provided above)

Right now there is no functionality, it's all static. Is there anything else you would like me to add/do for this issue?

**Comment by JoeDravarol** [comment]
Great, I'll open a PR for this issue.
