### ISSUE TITLE
Add dummy JSON data for development.

### ISSUE THREAD

**Issue by intelagense** [Caleb-Cohen/Together#55]
We should be able to provide some dummy JSON data for the `npm run devstart` command to enable developers to test the code without needing discord auth or mongo secrets and keys

**Comment by Caleb-Cohen** [comment]
I agree, let's finish the event form MVP and then can build some examples.

**Comment by WinstonHall** [comment]
This has some of that .env.development smell all over it. 
We will be running one terminal for the entire Next project.

**Comment by Caleb-Cohen** [comment]
I'll take this on!

**Comment by code2244** [comment]
I will like to help in this issue.
