### ISSUE TITLE
Git workflow & Repo protection.

### ISSUE THREAD

**Issue by WinstonHall** [Caleb-Cohen/Together#63]
There are settings you can add making code submitted be locked out from finalizing any sorta merge to our repo. 
Example - one of the settings just gates the code until a set number of people sign off on the changes.
There are a few more but I'm drawing blank on it atm.

**Comment by Caleb-Cohen** [comment]
I found the section you mention. Will talk with @intelagense and update.

**Comment by Caleb-Cohen** [comment]
Going to close this as we had a discussion and outline for some fixes. If there's more to discuss let's open a discussion.
