### ISSUE TITLE
Re-Organize file format

### ISSUE THREAD

**Issue by Caleb-Cohen** [Caleb-Cohen/Together#69]
Using this format: https://github.com/fullstack-hy2020/create-app

Task should be started shortly after we do the add-event-form merge, but you can start to familiarize yourself with the formatting required.

**Comment by JoeDravarol** [comment]
Tasks related for this issue can be found here #77.

This issue only entail:
* Creating a server folder and move anything backend related into said folder.

**Comment by JoeDravarol** [comment]
> All of the tasks for re-organizing file structure can be found in issue #77.
> 
> Task related to this issue:
> 
>     * Creating a server folder and move anything backend related into said folder.

@Caleb-Cohen Hope you are alright with this and approve of the spliting all of the main re-organizing task into separate issue and PR so that it will be easier to manage.

**Comment by Caleb-Cohen** [comment]
I've got PR https://github.com/Caleb-Cohen/Together/pull/85. We need to assess the build folder location because we are server-side rendering.
