### ISSUE TITLE
Create event addition form to submit event event objects to database

### ISSUE THREAD

**Issue by intelagense** [Caleb-Cohen/Together#7]
Might have to update the model at the same time.

**Comment by InstincDev** [comment]
I will complete this task.

**Comment by intelagense** [comment]
I added a whiteboard, discussion #9 , for reference

**Comment by Caleb-Cohen** [comment]
@InstincDev I've created the eventSchema. Would love your thoughts! Issue related for discussion can be found at #12 I've created a branch called Schema as well that includes the information.
