### ISSUE TITLE
Re-organize React files/folders with Bulletproof React guideline

### ISSUE THREAD

**Issue by JoeDravarol** [Caleb-Cohen/Together#83]
This is an issue representing task 3 of issue #77

# Task
* Re-organize files/folders to match [Bulletproof React](https://github.com/alan2207/bulletproof-react/blob/master/docs/project-structure.md) project structure.
* Configure the project to use [absolute import](https://saurabhshah23.medium.com/react-app-with-absolute-paths-using-jsconfig-json-2b07b1cb24d4); set to baseUrl to `src` and a global import of `@feature` following Bulletproof React guidelines.

**Comment by Caleb-Cohen** [comment]
I'll start working on this. Can assign to anyone else that's also interested.

**Comment by Caleb-Cohen** [comment]
I've got PR #85. We need to assess the build folder location because we are server-side rendering.

**Comment by Caleb-Cohen** [comment]
@JoeDravarol are we abandoning absolute import?

**Comment by JoeDravarol** [comment]
> @JoeDravarol are we abandoning absolute import?

No. Absolute import has been configured for the project in #86 with `jsconfig.json`. We are abandoning the [import alias path](https://stackoverflow.com/a/63068531) that was part of [Bulletproof React project configuration](https://github.com/alan2207/bulletproof-react/blob/master/docs/project-configuration.md#absolute-imports) guideline due to [CRA](https://create-react-app.dev/docs/getting-started/) lack of native support for [alias path](https://stackoverflow.com/a/63068531).

@Caleb-Cohen In #86, I noticed we are missing some folders; the `components` folder for resuable components, `routes` folder for routes configuration and the `context` folder for the application providers/context. Should we not create them before hand or do you want developers' to create the folder when we need them.

**Comment by Caleb-Cohen** [comment]
> @Caleb-Cohen In #86, I noticed we are missing some folders; the `components` folder for resuable components, `routes` folder for routes configuration and the `context` folder for the application providers/context. Should we not create them before hand or do you want developers' to create the folder when we need them.

I have them in my repo. You cannot add empty folders to a Git repo. https://git.wiki.kernel.org/index.php/GitFaq#Can_I_add_empty_directories.3F
