### ISSUE TITLE
Have event form grab auth information for display name

### ISSUE THREAD

**Issue by Caleb-Cohen** [Caleb-Cohen/Together#84]
**Please provide a summary of the feature**
When the user is completing the add-event form have the form use the logged-in user's discord display name instead of having it manually entered.

**Are there any potential issues you foresee with this feature**
I could foresee some issues with how the backend interacts with the frontend.

**Is this feature related to any current or past issues? Please provide the #**
Related to discord Auth: https://github.com/Caleb-Cohen/Together/pull/21
Add-event form: https://github.com/Caleb-Cohen/Together/pull/82

@winstonhall please comment so I can assign it.

**Comment by WinstonHall** [comment]
beep

**Comment by Caleb-Cohen** [comment]
> beep

boop

**Comment by luciousmc** [comment]
I'd like to work on this as well

**Comment by Caleb-Cohen** [comment]
> I'd like to work on this as well

I'm working on this ~10am CST, would you be available?

**Comment by luciousmc** [comment]
Unfortunately, I'm not available today. You can go on ahead if you wish.
