### ISSUE TITLE
addEvent form data and event.js schema adjustments determined while working on calendar view

### ISSUE THREAD

**Issue by intelagense** [Caleb-Cohen/Together#92]
Modifications for MVP readiness. 

General guidelines are below.

addEvent form can combine "date" and "startTime" into a single date object key-value pair ("seedDate" in the schema) for the "seed" date before storing it in MongoDB (reference "date" in current dummy JSON)

We will be able to calculate recurring events based on the time and day of the seed date 

Can remove or comment out endTime for MVP purposes 

endDate should be added to the addEvent form and schema for the final end date of the event (greyed out or hidden if not recurring)

**Comment by intelagense** [comment]
@InstincDev @MatthewBozin 👀 let me know if you have time for this.

**Comment by MatthewBozin** [comment]
Can you provide an example of what a "seedDate" would look like?

**Comment by intelagense** [comment]
https://github.com/Caleb-Cohen/Together/blob/refractor/client/src/test/events.json

@MatthewBozin right now we have a javascript date object for each event in the dummy data. 

      "date": "2022-12-08T03:01:59.368Z",

I  believe this is ISO 8601

**Comment by intelagense** [comment]
The seed date can be in this format because it will include the date and time of the _first_ occurrence of the recurring event.

**Comment by intelagense** [comment]
(linking this issue to discussion #108)

**Comment by Caleb-Cohen** [comment]
Closed as not planned.
