### ISSUE TITLE
Update package.json name & description

### ISSUE THREAD

**Issue by JoeDravarol** [Caleb-Cohen/Together#98]
# Summary
Update the root package.json file name and description.

# Task
* Change **name** from `binary-upload-boom` to `Together`.
* Update the description to explain what Together is. A description can be found in the repo or in the **Readme.md** file.

# To contribute
Fork from the `refractor` branch. When completed, make a pull request comparing to the `refractor` branch. Instructions on how to contribute can be found [here](https://github.com/Caleb-Cohen/Together/blob/main/CONTRIBUTING.md). If there's any question you can ask here or over in the Together Discord thread.

**Comment by Caleb-Cohen** [comment]
fixed in #101
